In [2]:
!where python

C:\Users\ett\.ms-ad\python.exe
C:\Users\ett\AppData\Local\Programs\Python\Python313\python.exe
C:\Users\ett\AppData\Local\Microsoft\WindowsApps\python.exe

In [3]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv(r"C:\Users\ett\Downloads\07.18 Lagos Business Database - FMF (1)-0 - 07.18 Lagos Business Database - FMF (1)-0.csv",dtype='object')

In [5]:
df

,company_name,Sub Sector,Industrial Sector,address,state,city,area,phone_number,alt_phone_number,website,contact_person,email_address
0,LetsDesign Studios,3d Art Project,3d Art Project,"24, Jaiyeola Street, Ajao Estate, Lagos Mainla...",Lagos,Lagos Mainland,Ajao Estate,8125609352,NaN,http://www.letsdesignstudios.com,LetsDesign Studios,info@letsdesignstudios.com
1,a/z pluz painting concept,3d Art Project,3d Art Project,"30a adeba, Church street adeba, Admiralty Way,...",Lagos,Eti Osa,"Admiralty Way, Lekki Phase I",8034667588,NaN,NaN,NaN,abduladams947@gmail.com
2,a z plus painting concepts,3d Art Project,3d Art Project,"30a, adeba, Agungi, Lekki, Ibeju Lekki, Lagos,...",Lagos,Ibeju Lekki,"Agungi, Lekki",8034667588,NaN,NaN,NaN,abduladams947@gmail.com
3,a z plus painting concepts,3d Art Project,3d Art Project,"30a, adeba, Ahmadu Bello Way, Eti Osa, Lagos, ...",Lagos,Eti Osa,Ahmadu Bello Way,8034667588,NaN,NaN,NaN,abduladams947@gmail.com
4,enimayo 3d Art program,3d Art Project,3d Art Project,"10, adenuga, Ajiboje, Badagry, Lagos, nigeria",Lagos,Badagry,Ajiboje,7058457749,NaN,NaN,NaN,rmayowa6@gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...
543173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,amutaabahsunday@yahoo.com
543174,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tracy_4jesus@yahoo.com
543175,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,loriweyimi@yahoo.com
543176,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,titiomage@yahoo.com
543177,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,usmansaheed@yahoo.com

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 543178 entries, 0 to 543177
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   company_name       519737 non-null  object
 1   Sub Sector         369849 non-null  object
 2   Industrial Sector  33470 non-null   object
 3   address            519741 non-null  object
 4   state              519741 non-null  object
 5   city               519577 non-null  object
 6   area               368390 non-null  object
 7   phone_number       519732 non-null  object
 8   alt_phone_number   180918 non-null  object
 9   website            54433 non-null   object
 10  contact_person     376857 non-null  object
 11  email_address      277317 non-null  object
dtypes: object(12)
memory usage: 49.7+ MB

In [7]:
df.describe(include='all')

,company_name,Sub Sector,Industrial Sector,address,state,city,area,phone_number,alt_phone_number,website,contact_person,email_address
count,519737,369849,33470,519741,519741,519577,368390,519732,180918,54433,376857,277317
unique,442824,38916,33,437765,2,97,4683,399018,156648,37290,184941,170831
top,The Redeemed Christian Church Of God,"Churches,Religion",Agriculture,Ikeja Ikeja Lagos Nigeria,Lagos,Alimosho,Omole Phase 1,7002255822,12808822,http://www.rccg.org,m,bale2004@yahoo.com
freq,1062,6117,7098,1434,519740,70755,16385,130,123,722,4533,7908

In [8]:
df.dtypes

company_name         object
Sub Sector           object
Industrial Sector    object
address              object
state                object
city                 object
area                 object
phone_number         object
alt_phone_number     object
website              object
contact_person       object
email_address        object
dtype: object

In [9]:
df.isnull().sum()

company_name          23441
Sub Sector           173329
Industrial Sector    509708
address               23437
state                 23437
city                  23601
area                 174788
phone_number          23446
alt_phone_number     362260
website              488745
contact_person       166321
email_address        265861
dtype: int64

In [10]:
avg_missing_data=df.isnull().mean()
avg_missing_data

company_name         0.043155
Sub Sector           0.319102
Industrial Sector    0.938381
address              0.043148
state                0.043148
city                 0.043450
area                 0.321788
phone_number         0.043164
alt_phone_number     0.666927
website              0.899788
contact_person       0.306200
email_address        0.489455
dtype: float64

In [11]:
industrialsector_freq=df['Industrial Sector'].value_counts().idxmax()
industrialsector_freq

'Agriculture'

In [12]:
df['Industrial Sector'].replace(np.nan,'Agriculture',inplace=True)

C:\Users\ett\AppData\Local\Temp\ipykernel_2920\3394952267.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Industrial Sector'].replace(np.nan,'Agriculture',inplace=True)

In [13]:
df['state'].value_counts()

state
Lagos    519740
state         1
Name: count, dtype: int64

In [14]:
df['state'].value_counts().idxmax()

'Lagos'

In [15]:
df['state'].replace(np.nan,'Lagos',inplace=True)

C:\Users\ett\AppData\Local\Temp\ipykernel_2920\509288146.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['state'].replace(np.nan,'Lagos',inplace=True)

In [16]:
df['city'].value_counts().idxmax()

'Alimosho'

In [17]:
df['city'].replace(np.nan,'Alimosho',inplace=True)

C:\Users\ett\AppData\Local\Temp\ipykernel_2920\3755946336.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['city'].replace(np.nan,'Alimosho',inplace=True)

In [18]:
df['website']=df['website'].fillna('http://'+df['company_name']+'.com')
df['website']

0              http://www.letsdesignstudios.com
1          http://a/z pluz painting concept.com
2         http://a z plus painting concepts.com
3         http://a z plus painting concepts.com
4             http://enimayo 3d Art program.com
                          ...
543173                                      NaN
543174                                      NaN
543175                                      NaN
543176                                      NaN
543177                                      NaN
Name: website, Length: 543178, dtype: object

In [19]:
df['email_address']=df['email_address'].fillna(df['company_name']+'@gmail.com')
df['email_address']

0         info@letsdesignstudios.com
1            abduladams947@gmail.com
2            abduladams947@gmail.com
3            abduladams947@gmail.com
4                 rmayowa6@gmail.com
                     ...
543173     amutaabahsunday@yahoo.com
543174        tracy_4jesus@yahoo.com
543175          loriweyimi@yahoo.com
543176           titiomage@yahoo.com
543177         usmansaheed@yahoo.com
Name: email_address, Length: 543178, dtype: object

In [20]:
df['area'].value_counts().idxmax()

'Omole Phase 1'

In [21]:
df['area'].replace(np.nan,'Omole Phase 1',inplace=True)

C:\Users\ett\AppData\Local\Temp\ipykernel_2920\2641863510.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['area'].replace(np.nan,'Omole Phase 1',inplace=True)

In [22]:
df['phone_number']=df['phone_number'].fillna('Not Available')

In [23]:
df['company_name']=df['company_name'].fillna('Not Available')

In [24]:
df.dropna(subset=['alt_phone_number'],axis=0,inplace=True)

In [25]:
df.dropna(subset=['contact_person'],axis=0,inplace=True)

In [26]:
df['Sub Sector'].value_counts().idxmax()

'Churches,Religion'

In [27]:
df['Sub Sector'].replace(np.nan,'Churches,Religion',inplace=True)

C:\Users\ett\AppData\Local\Temp\ipykernel_2920\499629955.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Sub Sector'].replace(np.nan,'Churches,Religion',inplace=True)

In [28]:
df.isnull().sum()

company_name         0
Sub Sector           0
Industrial Sector    0
address              0
state                0
city                 0
area                 0
phone_number         0
alt_phone_number     0
website              0
contact_person       0
email_address        0
dtype: int64

In [29]:
df

,company_name,Sub Sector,Industrial Sector,address,state,city,area,phone_number,alt_phone_number,website,contact_person,email_address
9,Westklass Studios,"3D Art Project,Entertainment,Media and Enterta...",3d Art Project,"168, Akarigbo Road, Ajegunle, Ajeromi Ifelodun...",Lagos,Ajeromi Ifelodun,Ajegunle,7031551900,8073621935,http://Westklass Studios.com,Salvage O. Johnson,Westklass Studios@gmail.com
12,Morningstar technical work,Ac Repair Services,Ac Repair Services,"12, road 12 lekki phase 1, Admiralty Way, Lekk...",Lagos,Eti Osa,"Admiralty Way, Lekki Phase I",8027886607,8135966632,http://Morningstar technical work.com,Adebayo,morningstar6607@gmail.com
14,Koolarena Resources Limited,Ac Repair Services,Ac Repair Services,"24, Omodara Avenue, Iju Ishaga, Agege, Lagos, ...",Lagos,Agege,Iju Ishaga,8027400868,8115033001,http://koolarena.com/,Bankole,info@koolarena.com
16,highercool,Ac Repair Services,Ac Repair Services,"41, AIT Road, Omeregie, Bus Stop, off kola Bus...",Lagos,Alimosho,Abeokuta Expressway,8033510165,8033914670,http://highercool.com/,Emeka,highercool17@gmail.com
19,Liberty Services International,Ac Repair Services,Ac Repair Services,"7, George Street, Oniapnu, Shomolu, Lagos, Nig...",Lagos,Shomolu,Oniapnu,8023864246,7065318039,http://Liberty Services International.com,Johnson,libertyservicesinternational@gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...
443345,ZOBOClassic,"Churches,Religion",Agriculture,KM 4 LASU/Isheri Express Way by General Hospit...,Lagos,Lagos Mainland,Omole Phase 1,8142415844,8123144841,http://ZOBOClassic.com,ZOBOClassic,ZOBOClassic@gmail.com
443348,Zaccheus Onumbia Diabiezue Memorial Libraries ...,"Churches,Religion",Agriculture,Awolowo Road Ikoyi 196 Awolowo Road Ikoyi Et...,Lagos,Eti Osa,Omole Phase 1,8023297111,01â€“ 46317,http://www.zodml.org,ZODML,info@zodml.org
443353,Hartz Cleaners Supply Ltd,"Churches,Religion",Agriculture,Oluwaleyimu st Omole Phase 1 Ikeja Lagos Nigeria,Lagos,Ikeja,Omole Phase 1,8130229343,7064508854,http://Hartz Cleaners Supply Ltd.com,Zoheir OR Tolu,info@hartzcleanerssupply.com
443363,352ng,"Churches,Religion",Agriculture,Luth Lagos. Surulere Lagos Nigeria,Lagos,Surulere,Omole Phase 1,7083316921,9097343064,http://www.352.com.ng,Zubair,editor@352.com.ng
443365,didijobs,"Churches,Religion",Agriculture,33 road b close house 5 egbeda lagos Alimosho...,Lagos,Alimosho,Omole Phase 1,8141344709,8090876041,http://www.didijobs.com,zubairadamsohikere,contact@didijobs.com

In [30]:
df[['company_name','address']]

,company_name,address
9,Westklass Studios,"168, Akarigbo Road, Ajegunle, Ajeromi Ifelodun..."
12,Morningstar technical work,"12, road 12 lekki phase 1, Admiralty Way, Lekk..."
14,Koolarena Resources Limited,"24, Omodara Avenue, Iju Ishaga, Agege, Lagos, ..."
16,highercool,"41, AIT Road, Omeregie, Bus Stop, off kola Bus..."
19,Liberty Services International,"7, George Street, Oniapnu, Shomolu, Lagos, Nig..."
...,...,...
443345,ZOBOClassic,KM 4 LASU/Isheri Express Way by General Hospit...
443348,Zaccheus Onumbia Diabiezue Memorial Libraries ...,Awolowo Road Ikoyi 196 Awolowo Road Ikoyi Et...
443353,Hartz Cleaners Supply Ltd,Oluwaleyimu st Omole Phase 1 Ikeja Lagos Nigeria
443363,352ng,Luth Lagos. Surulere Lagos Nigeria
443365,didijobs,33 road b close house 5 egbeda lagos Alimosho...

In [31]:
df['company_name']=df['company_name'].str.title()

In [32]:
df['address']=df['address'].str.title()

In [33]:
df=df.apply(lambda x:x.str.strip())

In [34]:
df.loc[df['Sub Sector'].str.contains('Writers|Womens Wear',regex=True)]

,company_name,Sub Sector,Industrial Sector,address,state,city,area,phone_number,alt_phone_number,website,contact_person,email_address
29781,Dbc Comic Company,"Arts,Writers",Agriculture,"247, Egan Igando Road, Alimosho, Lagos, Nigeria",Lagos,Alimosho,Omole Phase 1,9090200034,8184014206,http://DBC Comic Company.com,Mrs Emmanuel,DBC Comic Company@gmail.com
87468,Posh Makeup And Beauty Studio,"Beauty Parlours,Make Up Artists,Womens Wear",Agriculture,"5, Araba Street, Egbeda, Alimosho, Lagos, Nigeria",Lagos,Alimosho,Egbeda,9023041123,8152099783,http://Posh Makeup And Beauty Studio.com,Oyin Adedoyin,poshsays1@gmail.com
111886,Figures Boutique,"Boutiques,Clothing,Womens Wear",Agriculture,"56, Akowonjo Road, Egbeda, Alimosho, Lagos, Ni...",Lagos,Alimosho,Egbeda,8038020911,7083337388,http://Figures Boutique.com,Angela Figures,afes99@yahoo.co.uk
111890,I K Boutique,"Boutiques,Clothing,Womens Wear",Agriculture,"22, Majolate Street, Ilupeju, Mushin, Lagos, N...",Lagos,Mushin,Ilupeju,8023820974,8035292059,http://I K Boutique.com,I K,I K Boutique@gmail.com
111897,Mummy Angel,"Boutiques,Clothing,Womens Wear",Agriculture,"1, Tiwalade Street, Shogunle, Oshodi Isolo, La...",Lagos,Oshodi Isolo,Shogunle,8102906893,8031913372,http://Mummy Angel.com,Mr Fred,Mummy Angel@gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...
328043,Koinage Media,"Media Communication,Writers",Agriculture,"6A, Ebun Oluwa Street Off Haruna Street Off Co...",Lagos,Ikeja,Omole Phase 1,8137237119,8127894973,http://www.koinagemedia.com,Patrick,info@koinagemedia.com
328046,King'S Heir Entertainment,"Media Communication,Writers",Agriculture,"26, Adebowale Street, Ojodu, Lagos Mainland, L...",Lagos,Lagos Mainland,Ojodu,7061170195,8054390699,http://King's Heir Entertainment.com,Price Paul Odigbo,King's Heir Entertainment@gmail.com
329500,Mai Provider Media,"Modeling Agencies,Writers",Agriculture,Gobi Shopping Mall Ikotun Alimosho Lagos Nigeria,Lagos,Alimosho,Ikotun,8189295197,7033452392,http://Mai Provider Media.com,Jide,myprovidermedia1@gmail.com
369805,Tjmax Fashions,Womens Wear,Agriculture,"Shop 80, First Floor,Bristol Plaza, Broad Stre...",Lagos,Lagos Island,Broad Street,8183353186,8133026056,http://Tjmax Fashions.com,Iyabo,iyabodet@yahoo.co.uk
369833,Civ Films,Writers,Agriculture,"20, Segun, Idimu Titun, Alimosho, Lagos, Nigeria",Lagos,Alimosho,Idimu Titun,8025362660,8071436257,http://www.gregscripts.blogspot.com.ng,Greg,greafma@gmail.com

In [35]:
df['Industrial Sector'].unique()

array(['3d Art Project', 'Ac Repair Services', 'Accessories',
       'Accident And Emergencies', 'Accommodation', 'Accountants',
       'Active Life', 'Administration Of Estate', 'Adult School',
       'Advanced Books', 'Adventure Sports', 'Advertising Agencies',
       'Advocate', 'Fitness', 'Restaurants', 'Agriculture', 'Aviation',
       'Food & Beverage', 'Fashion', 'Steel', 'Healthcare', 'Hospitality',
       'Religion', 'Computer', 'Construction', 'Design', 'Oil & Gas',
       'Real Estate', 'Education', 'Transport & Logistics', 'Retail',
       'Manufacturing', 'Storage'], dtype=object)

In [36]:
df_group=df.groupby(['area', 'Industrial Sector']).size().reset_index(name='count')

In [37]:
df_group

               area     Industrial Sector  count
0         1004 AREA           Agriculture      3
1      1004 Estates           Agriculture      4
2      1004 Estates           Real Estate      1
3        1st Avenue           Agriculture      3
4          1st Gate           Agriculture      9
...             ...                   ...    ...
6951   ketu Ijaniki           Agriculture      1
6952  kola Alagbado           Agriculture      1
6953           Ã’gba         Accommodation      1
6954           Ã’gba  Advertising Agencies      2
6955           Ã’gba           Agriculture     26

[6956 rows x 3 columns]

In [38]:
df_group=df_group.sort_values(['area', 'count'], ascending=False)
df_group

               area     Industrial Sector  count
6955           Ã’gba           Agriculture     26
6954           Ã’gba  Advertising Agencies      2
6953           Ã’gba         Accommodation      1
6952  kola Alagbado           Agriculture      1
6951   ketu Ijaniki           Agriculture      1
...             ...                   ...    ...
5          1st Gate              Aviation      1
3        1st Avenue           Agriculture      3
1      1004 Estates           Agriculture      4
2      1004 Estates           Real Estate      1
0         1004 AREA           Agriculture      3

[6956 rows x 3 columns]

In [39]:
df[df['company_name'].str.contains('Hartz Cleaners Supply Ltd')]

,company_name,Sub Sector,Industrial Sector,address,state,city,area,phone_number,alt_phone_number,website,contact_person,email_address
443353,Hartz Cleaners Supply Ltd,"Churches,Religion",Agriculture,Oluwaleyimu St Omole Phase 1 Ikeja Lagos Nigeria,Lagos,Ikeja,Omole Phase 1,8130229343,7064508854,http://Hartz Cleaners Supply Ltd.com,Zoheir OR Tolu,info@hartzcleanerssupply.com

In [40]:
df.loc[443353] = df.loc[443353].replace({'Churches,Religion':'Manufacturing','Agriculture':'retail and wholesale trade'})

In [41]:
df[df['company_name'].str.contains('Hartz Cleaners Supply Ltd')]

,company_name,Sub Sector,Industrial Sector,address,state,city,area,phone_number,alt_phone_number,website,contact_person,email_address
443353,Hartz Cleaners Supply Ltd,Manufacturing,retail and wholesale trade,Oluwaleyimu St Omole Phase 1 Ikeja Lagos Nigeria,Lagos,Ikeja,Omole Phase 1,8130229343,7064508854,http://Hartz Cleaners Supply Ltd.com,Zoheir OR Tolu,info@hartzcleanerssupply.com

In [42]:
df

,company_name,Sub Sector,Industrial Sector,address,state,city,area,phone_number,alt_phone_number,website,contact_person,email_address
9,Westklass Studios,"3D Art Project,Entertainment,Media and Enterta...",3d Art Project,"168, Akarigbo Road, Ajegunle, Ajeromi Ifelodun...",Lagos,Ajeromi Ifelodun,Ajegunle,7031551900,8073621935,http://Westklass Studios.com,Salvage O. Johnson,Westklass Studios@gmail.com
12,Morningstar Technical Work,Ac Repair Services,Ac Repair Services,"12, Road 12 Lekki Phase 1, Admiralty Way, Lekk...",Lagos,Eti Osa,"Admiralty Way, Lekki Phase I",8027886607,8135966632,http://Morningstar technical work.com,Adebayo,morningstar6607@gmail.com
14,Koolarena Resources Limited,Ac Repair Services,Ac Repair Services,"24, Omodara Avenue, Iju Ishaga, Agege, Lagos, ...",Lagos,Agege,Iju Ishaga,8027400868,8115033001,http://koolarena.com/,Bankole,info@koolarena.com
16,Highercool,Ac Repair Services,Ac Repair Services,"41, Ait Road, Omeregie, Bus Stop, Off Kola Bus...",Lagos,Alimosho,Abeokuta Expressway,8033510165,8033914670,http://highercool.com/,Emeka,highercool17@gmail.com
19,Liberty Services International,Ac Repair Services,Ac Repair Services,"7, George Street, Oniapnu, Shomolu, Lagos, Nig...",Lagos,Shomolu,Oniapnu,8023864246,7065318039,http://Liberty Services International.com,Johnson,libertyservicesinternational@gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...
443345,Zoboclassic,"Churches,Religion",Agriculture,Km 4 Lasu/Isheri Express Way By General Hospit...,Lagos,Lagos Mainland,Omole Phase 1,8142415844,8123144841,http://ZOBOClassic.com,ZOBOClassic,ZOBOClassic@gmail.com
443348,Zaccheus Onumbia Diabiezue Memorial Libraries ...,"Churches,Religion",Agriculture,Awolowo Road Ikoyi 196 Awolowo Road Ikoyi Et...,Lagos,Eti Osa,Omole Phase 1,8023297111,01â€“ 46317,http://www.zodml.org,ZODML,info@zodml.org
443353,Hartz Cleaners Supply Ltd,Manufacturing,retail and wholesale trade,Oluwaleyimu St Omole Phase 1 Ikeja Lagos Nigeria,Lagos,Ikeja,Omole Phase 1,8130229343,7064508854,http://Hartz Cleaners Supply Ltd.com,Zoheir OR Tolu,info@hartzcleanerssupply.com
443363,352Ng,"Churches,Religion",Agriculture,Luth Lagos. Surulere Lagos Nigeria,Lagos,Surulere,Omole Phase 1,7083316921,9097343064,http://www.352.com.ng,Zubair,editor@352.com.ng
443365,Didijobs,"Churches,Religion",Agriculture,33 Road B Close House 5 Egbeda Lagos Alimosho...,Lagos,Alimosho,Omole Phase 1,8141344709,8090876041,http://www.didijobs.com,zubairadamsohikere,contact@didijobs.com

In [43]:
df.to_csv('Tanta Innovative Document.csv',index=False)